/** inputFields — Definitions for all 11 KOI input parameters. */
export const INPUT_FIELDS = [
  {
    key: "koi_period",
    label: "Orbital Period",
    unit: "days",
    min: 0.5,
    max: 1000,
    step: 0.1,
    placeholder: "e.g., 289.9",
    tooltip: "Time in days for one complete orbit around the host star",
  },
  {
    key: "koi_duration",
    label: "Transit Duration",
    unit: "hrs",
    min: 0.01,
    max: 72,
    step: 0.01,
    placeholder: "e.g., 7.4",
    tooltip: "Total time the planet spends crossing the stellar disk",
  },
  {
    key: "koi_depth",
    label: "Transit Depth",
    unit: "ppm",
    min: 10,
    max: 1000000,
    step: 1,
    placeholder: "e.g., 492.0",
    tooltip: "Fraction of stellar flux blocked during transit (parts per million)",
  },
  {
    key: "koi_ror",
    label: "Planet/Star Radius Ratio",
    unit: "",
    min: 0.001,
    max: 0.5,
    step: 0.001,
    placeholder: "e.g., 0.048",
    tooltip: "Ratio of planet radius to host star radius derived from transit shape",
  },
  {
    key: "koi_impact",
    label: "Impact Parameter",
    unit: "",
    min: 0,
    max: 1.1,
    step: 0.01,
    placeholder: "e.g., 0.21",
    tooltip: "Sky-projected distance of planet trajectory from stellar center (0 = direct crossing)",
  },
  {
    key: "koi_model_snr",
    label: "Signal-to-Noise Ratio",
    unit: "",
    min: 1,
    max: 10000,
    step: 0.1,
    placeholder: "e.g., 17.1",
    tooltip: "Statistical significance of the detected transit signal",
  },
  {
    key: "koi_num_transits",
    label: "Number of Transits",
    unit: "",
    min: 1,
    max: 500,
    step: 1,
    placeholder: "e.g., 3",
    tooltip: "Total number of transit events observed during the mission",
  },
  {
    key: "koi_steff",
    label: "Stellar Temperature",
    unit: "K",
    min: 2500,
    max: 10000,
    step: 1,
    placeholder: "e.g., 5793",
    tooltip: "Surface temperature of the host star in Kelvin",
  },
  {
    key: "koi_slogg",
    label: "Stellar Surface Gravity",
    unit: "",
    min: 1.0,
    max: 5.5,
    step: 0.01,
    placeholder: "e.g., 4.44",
    tooltip: "Log base 10 of the host star's surface gravitational acceleration",
  },
  {
    key: "koi_srad",
    label: "Stellar Radius",
    unit: "R☉",
    min: 0.1,
    max: 10,
    step: 0.01,
    placeholder: "e.g., 0.98",
    tooltip: "Physical radius of the host star relative to our Sun",
  },
  {
    key: "koi_smass",
    label: "Stellar Mass",
    unit: "M☉",
    min: 0.1,
    max: 5,
    step: 0.01,
    placeholder: "e.g., 0.97",
    tooltip: "Physical mass of the host star relative to our Sun",
  },
  {
    key: "ra",
    label: "Right Ascension",
    unit: "°",
    min: 0,
    max: 360,
    step: 0.01,
    placeholder: "e.g., 291.0",
    tooltip: "Right ascension of the target star (J2000)",
    optional: true,
  },
  {
    key: "dec",
    label: "Declination",
    unit: "°",
    min: -90,
    max: 90,
    step: 0.01,
    placeholder: "e.g., 48.14",
    tooltip: "Declination of the target star (J2000)",
    optional: true,
  },
  {
    key: "koi_score",
    label: "Disposition Score",
    unit: "",
    min: 0,
    max: 1,
    step: 0.01,
    placeholder: "e.g., 0.9",
    tooltip: "Score indicating confidence the signal is a real planet (0 = likely FP, 1 = likely confirmed)",
    optional: true,
  },
];
